export const schedule = {







    nursery: {
        bell: [
            "First Bell",
            "Second Bell",
            "Assembly Bell",
            "Assembly End",
            "1st Period",
            "2nd Period",
            "3rd Period",
            "Break",
            "4th Period",
            "5th Period",
            "Lunch Break",
            "6th Period",
            "7th Period",
            "End of School Day"
        ],
        localTime: [
            "1:00 LT",
            "1:45 LT",
            "2:00 LT",
            "2:30 LT",
            "3:15 LT",
            "3:50 LT",
            "4:25 LT",
            "4:45 LT",
            "5:25 LT",
            "6:00 LT",
            "7:20 LT",
            "8:00 LT",
            "8:35 LT",
            "9:05 LT"
        ],
        Schedule: [
            "School Gates Open",
            "Teachers Sign in",
            "School Gates Close",
            "Students to their Classes",
            "End of 1st Period",
            "End of 2nd Period",
            "End of 3rd Period",
            "End of Break",
            "End of 4th Period",
            "End of 5th Period",
            "End of Lunch Break",
            "End of 6th Period",
            "End of 7th Period",
            "End of 8th Period"
        ],
        monday: [
            "-",
            "-",
            "-",
            "-",
            "Engilsh",
            "Math",
            "Art",
            "-",
            "Amharic",
            "sport",
            "-",
            "Writing",
            "Engilsh",
            "-"
        ],
        tuesday: [
            "-",
            "-",
            "-",
            "-",
            "Engilsh",
            "Math",
            "Art",
            "-",
            "Amharic",
            "sport",
            "-",
            "Writing",
            "Engilsh",
            "-"
        ],
        wednesday: [
            "-",
            "-",
            "-",
            "-",
            "Engilsh",
            "Math",
            "Art",
            "-",
            "Amharic",
            "sport",
            "-",
            "Writing",
            "Engilsh",
            "-"
        ],
        thursday: [
            "-",
            "-",
            "-",
            "-",
            "Engilsh",
            "Math",
            "Art",
            "-",
            "Amharic",
            "sport",
            "-",
            "Writing",
            "Engilsh",
            "-"
        ],
        friday: [
            "-",
            "-",
            "-",
            "-",
            "Engilsh",
            "Math",
            "Art",
            "-",
            "Amharic",
            "sport",
            "-",
            "Writing",
            "Engilsh",
            "-"
        ]
    },
    grade_1_to_4: {
        bell: [
            "First Bell",
            "Second Bell",
            "Assembly Bell",
            "Assembly End",
            "1st Period",
            "2nd Period",
            "3rd Period",
            "Break",
            "4th Period",
            "5th Period",
            "Lunch Break",
            "6th Period",
            "7th Period",
            "End of School Day"
        ],
        localTime: [
            "1:00 LT",
            "1:45 LT",
            "2:00 LT",
            "2:30 LT",
            "3:15 LT",
            "3:50 LT",
            "4:25 LT",
            "4:45 LT",
            "5:25 LT",
            "6:00 LT",
            "7:20 LT",
            "8:00 LT",
            "8:35 LT",
            "9:05 LT"
        ],
        Schedule: [
            "School Gates Open",
            "Teachers Sign in",
            "School Gates Close",
            "Students to their Classes",
            "End of 1st Period",
            "End of 2nd Period",
            "End of 3rd Period",
            "End of Break",
            "End of 4th Period",
            "End of 5th Period",
            "End of Lunch Break",
            "End of 6th Period",
            "End of 7th Period",
            "End of 8th Period"
        ],
        monday: [
            "-",
            "-",
            "-",
            "-",
            "Engilsh",
            "Math",
            "general science",
            "-",
            "Amharic",
            "spoken english",
            "-",
            "IT",
            "Engilsh",
            "-"
        ],
        tuesday: [
            "-",
            "-",
            "-",
            "-",
            "Engilsh",
            "Math",
            "general science",
            "-",
            "Amharic",
            "spoken english",
            "-",
            "IT",
            "Engilsh",
            "-"
        ],
        wednesday: [
            "-",
            "-",
            "-",
            "-",
            "Engilsh",
            "Math",
            "general science",
            "-",
            "Amharic",
            "spoken english",
            "-",
            "IT",
            "Engilsh",
            "-"
        ],
        thursday: [
            "-",
            "-",
            "-",
            "-",
            "Engilsh",
            "Math",
            "general science",
            "-",
            "Amharic",
            "spoken english",
            "-",
            "IT",
            "Engilsh",
            "-"
        ],
        friday: [
            "-",
            "-",
            "-",
            "-",
            "Engilsh",
            "Math",
            "general science",
            "-",
            "Amharic",
            "spoken english",
            "-",
            "IT",
            "Engilsh",
            "-"
        ]
    },
    grade_5_to_8: {
        bell: [
            "First Bell",
            "Second Bell",
            "Assembly Bell",
            "Assembly End",
            "1st Period",
            "2nd Period",
            "3rd Period",
            "Break",
            "4th Period",
            "5th Period",
            "Lunch Break",
            "6th Period",
            "7th Period",
            "End of School Day"
        ],
        localTime: [
            "1:00 LT",
            "1:45 LT",
            "2:00 LT",
            "2:30 LT",
            "3:15 LT",
            "3:50 LT",
            "4:25 LT",
            "4:45 LT",
            "5:25 LT",
            "6:00 LT",
            "7:20 LT",
            "8:00 LT",
            "8:35 LT",
            "9:05 LT"
        ],
        Schedule: [
            "School Gates Open",
            "Teachers Sign in",
            "School Gates Close",
            "Students to their Classes",
            "End of 1st Period",
            "End of 2nd Period",
            "End of 3rd Period",
            "End of Break",
            "End of 4th Period",
            "End of 5th Period",
            "End of Lunch Break",
            "End of 6th Period",
            "End of 7th Period",
            "End of 8th Period"
        ],
        monday: [
            "-",
            "-",
            "-",
            "-",
            "Engilsh",
            "Math",
            "Civic",
            "-",
            "Amharic",
            "Physics",
            "-",
            "History",
            "Biology",
            "-"
        ],
        tuesday: [
            "-",
            "-",
            "-",
            "-",
            "Engilsh",
            "Math",
            "Civic",
            "-",
            "Amharic",
            "Physics",
            "-",
            "History",
            "Biology",
            "-"
        ],
        wednesday: [
            "-",
            "-",
            "-",
            "-",
            "Engilsh",
            "Math",
            "Civic",
            "-",
            "Amharic",
            "Physics",
            "-",
            "History",
            "Biology",
            "-"
        ],
        thursday: [
            "-",
            "-",
            "-",
            "-",
            "Engilsh",
            "Math",
            "Civic",
            "-",
            "Amharic",
            "Physics",
            "-",
            "History",
            "Biology",
            "-"
        ],
        friday: [
            "-",
            "-",
            "-",
            "-",
            "Engilsh",
            "Math",
            "Civic",
            "-",
            "Amharic",
            "Physics",
            "-",
            "History",
            "Biology",
            "-"
        ]
    },
}