# Generated by Django 5.0.6 on 2024-06-16 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="news",
            old_name="types",
            new_name="type_of_news",
        ),
    ]
